version: 2

project_name: natz-operator

builds:
  - id: operator
    binary: operator-{{.Os}}-{{.Arch}}
    main: cmd/operator/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    no_unique_dist_dir: true
  - id: account-server
    binary: account-server-{{.Os}}-{{.Arch}}
    main: cmd/account-server/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    no_unique_dist_dir: true

archives:
  - id: operator
    builds:
      - operator
    name_template: "operator_{{.Version}}_{{.Os}}_{{.Arch}}"
  - id: account-server
    builds:
      - account-server
    name_template: "account_server_{{.Version}}_{{.Os}}_{{.Arch}}"

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - operator
    image_templates:
      - "ghcr.io/katallaxie/{{.ProjectName}}/operator:latest"
      - "ghcr.io/katallaxie/{{.ProjectName}}/operator:{{.Tag}}"
      - "ghcr.io/katallaxie/{{.ProjectName}}/operator"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BINARY=operator-linux-amd64"
      - "--platform=linux/amd64"
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - account-server
    image_templates:
      - "ghcr.io/katallaxie/{{.ProjectName}}/account-server:latest"
      - "ghcr.io/katallaxie/{{.ProjectName}}/account-server:{{.Version}}"
      - "ghcr.io/katallaxie/{{.ProjectName}}/account-server"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BINARY=account-server-linux-amd64"
      - "--platform=linux/amd64"

gomod:
  proxy: false

release:
  draft: false

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "natz_checksums.txt"
