apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-server.fullname" . }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "account-server.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "account-server.fullname" . }}
    spec:
      serviceAccountName: {{ include "account-server.serviceAccountName" . }}
      containers:
      - name: account-server
        image: {{ default .Values.global.image.repository .Values.controller.image.repository }}:{{ default (include "account-server.defaultTag" .) .Values.controller.image.tag }}
        imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.controller.image.imagePullPolicy }}
        args: ["--metrics-bind-address", ":12003", "--health-probe-bind-address", ":12002"]
        env:
        - name: "NATS_URL"
          value: {{ .Values.controller.nats.url }}
        - name: "NATS_CREDS_FILE"
          value: "/etc/nats/user.creds"
        - name: "POD_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        volumeMounts:
        - name: "credentials"
          mountPath: "/etc/nats"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          {{- toYaml .Values.controller.securityContext | nindent 10 }}
      volumes:
      - name: "credentials"
        secret:
          defaultMode: 420
          secretName: {{ .Values.controller.secretName }}
          items:
          - key: "user.creds"
            path: "user.creds"
            mode: 420
       