apiVersion: v1
kind: Secret
metadata:
  name: gateway-north-secret
data:
  username: demo
  password: NjJlYjE2NWMwNzBhNDFkNWMxYjU4ZDlkM2Q3MjVjYTE=
---
apiVersion: natz.katallaxie.dev/v1alpha1
kind: NatsGateway
metadata:
  name: harry
spec:
  url: nats://nats.north:4222
  username:
    secretKeyRef:
      key: username
      name: gateway-north-secret
  password:
    secretKeyRef:
      key: password
      name: gateway-north-secret
