# permissions for end users to edit natsoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: natsoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: natz-operator
    app.kubernetes.io/part-of: natz-operator
    app.kubernetes.io/managed-by: kustomize
  name: natsoperator-editor-role
rules:
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators/status
  verbs:
  - get
