---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators/finalizers
  verbs:
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsusers/finalizers
  verbs:
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsusers/status
  verbs:
  - get
  - patch
  - update
