apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "natz-operator.fullname" . }}-manager-role
  labels:
  {{- include "natz-operator.labels" . | nindent 4 }}
rules:
- resources:
  - events
  apiGroups:
  - ""
  - events.k8s.io
  verbs:
  - create
  - patch
  - update
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch  
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natskeys
  - natsaccounts
  - natsoperators
  - natsusers
  - natsconfigs
  - natsgateways
  - natsactivations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsaccounts/finalizers
  - natsoperators/finalizers
  - natsusers/finalizers
  - natsconfigs/finalizers
  - natsgateways/finalizers
  - natsactivations/finalizers
  - natskeys/finalizers
  verbs:
  - update
- apiGroups:
  - natz.katallaxie.dev
  resources:
  - natsoperators/status
  - natsusers/status
  - natsgateways/status
  - natsconfigs/status
  - natsaccounts/status
  - natsactivations/status
  - natskeys/status
  verbs:
  - get
  - patch
  - update
  