apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "natz-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: natz-operator
    app.kubernetes.io/part-of: natz-operator
  {{- include "natz-operator.labels" . | nindent 4 }}